package project;
import java.util.*;

public class encryptpin2 {

	public static void main(String[] args) {
		                    /*Variables
		                      pin1= 1st generated pin
		                      pin2= 2nd generated pin
		                      pin3= 3rd generated pin
		                      pin4= 4th generated pin
		                      PIN= Number of digits of PIN
		                      newpin= Auto Generated Pin
		                     'd' string = digits(here d is used for extracting the digits out of random numbers)
		                      msg= The message inputed by the user for encryption
		                      emsg= Encrypted message which came as result
		                      c=counter*/
		  
		
				Scanner sc = new Scanner(System.in);
				String pin1,pin2,pin3,pin4;
				System.out.print("Enter the Value of Digits of PIN you want to Create :");
				int PIN=sc.nextInt();
				
				String d="";
				for(int i=0; i<PIN; i++)
				   {
					     d=d+(int)(Math.random()*10);
				   }
				pin1=d;
				System.out.println(pin1);
				d="";
				for(int i=0; i<PIN; i++)
				   {
					     d=d+(int)(Math.random()*10);
				   }
				pin2=d;
				System.out.println(pin2);
				d="";
				for(int i=0; i<PIN; i++)
				  {
					    d=d+(int)(Math.random()*10);
				   }
				pin3=d;
				System.out.println(pin3);
				d="";
				for(int i=0; i<PIN; i++)
				  {
					   d=d+(int)(Math.random()*10);
				  }
				pin4=d;
				System.out.println(pin3);
				d="";
				for(int i=0; i<PIN; i++)
				{
					d=d+(char)Math.min(Math.min(pin1.charAt(i),pin2.charAt(i)),Math.min(pin3.charAt(i),pin4.charAt(i)));
				}
				String newpin=d;
				System.out.println("The New Pin Generated By the system is : " +newpin);
				sc.nextLine();
				System.out.print("Enter The Message you want to encrypt :");
				String msg=sc.nextLine();
				msg=msg.toLowerCase();
				//System.out.println(msg);
                msg=msg.replaceAll(" ","");
				//System.out.println(msg);
				int c=0;
				String emsg="";
				d="";
				for(int i=0; i<msg.length(); i++)
				{
					char ch=msg.charAt(i);
					if(ch!=' ')
					{
						d=d+ch;
					}
				}
				msg=d;
				for(int i=0; i<msg.length(); i++,c++)
				{
					if(c==(newpin.length()-1))
						c=0;
					char ch1=msg.charAt(i);
					char ch2=newpin.charAt(c);
					int tmp=(int)ch2;
					tmp=tmp-48;
					ch1=(char)((int)ch1+tmp);
					if(ch1>122)
					{
						ch1=(char)((int)ch1-122);
						ch1=(char)((int)ch1+96);
					}
					emsg=emsg+ch1;
				}
				emsg=emsg.toUpperCase();
				System.out.println("Encrypted Message is :"+emsg);
			}
		
	}

